name: "Hello-world" # Workflow name
on: # when to trigger ``
    workflow_dispatch: # manual trigger 
jobs:
    say-hello-world: # Job name can be anything you like
        runs-on: ubuntu-latest # Runner
        steps:
            - name: Echo Hello World # step namer
              run: echo "Hello world" 