name: Workflow,Jobs,need(Job dependency)
on:
  workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: First Jobs
        run: |
          echo "Running Job-1"
          sudo apt-get update && sudo apt-get upgrade 
  job-2:
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Second Job which is depend on job-1
        run: print("This proves job-1 ran successfully")
        shell: python
